## PRUEBA PARCIAL 2
*soy CRISTAN ANDRES VILLACIS MENDOZA, desarrollo de software 4, esta es la prueba parcial 2, MACHEIN ES TODO

* machine learning -  1

## 01 - 1 pt
- Dado un array de elementos, escribir una función, que reciba dicho array como parámetro de entrada y devuelva el elemento repetido. Usando plain Python, sin ninguna librería.

In [3]:
import pandas as pd

def encontrar_primer_repetido(arr):
    """
    Retorna el primer elemento que se repite en la lista.
    """
    serie = pd.Series(arr)
    duplicados = serie[serie.duplicated()]
    if not duplicados.empty:
        print(f"🔁 Repetido encontrado: {duplicados.iloc[0]}")
        return duplicados.iloc[0]
    print("✅ No hay repetidos.")
    return None

# Test
encontrar_primer_repetido(['z', 'a', 'x', 'a', 'm', 'x'])


Elemento repetido: 3


## 02 - 1pt
- Genera una matriz con valores aleatorios de 0 a 100 de dimensiones 16x16
- Calcula los siguentes estadísticos en la matriz anterior, por fila (el resultado de cada uno debe ser un array de dimensiones 1x16)
  - Suma de los elementos de cada fila
  - Media de los elementos de cada fila
  - Valores mínimos de cada fila
  - Valores máximos de cada fila

In [5]:
import numpy as np

class MatrizAnalisis:
    def __init__(self, filas=16, columnas=16):
        self.data = np.random.randint(0, 101, (filas, columnas))
        print("📘 Matriz creada:\n", self.data)

    def estadisticas_por_fila(self):
        return {
            'suma': np.sum(self.data, axis=1),
            'media': np.mean(self.data, axis=1),
            'min': np.min(self.data, axis=1),
            'max': np.max(self.data, axis=1)
        }

# Uso
matriz = MatrizAnalisis()
res = matriz.estadisticas_por_fila()
for clave, val in res.items():
    print(f"📌 {clave.title()} por fila:\n{val}")


📘 Matriz creada:
 [[42 62 33 70 94 81 24 37 41 86 52 99  9 45 84 40]
 [76 54 88 83  0  1 46 64 19 74 36  0 78 22  7 35]
 [56 68 80 88  8 38 43  8 35 87 73 84 65 59 53 75]
 [93 35 69 12 89 73 24 83 31 35 42 43 80 16 15 17]
 [97 27 63 38 64 34 12 39 21 25 94 17 76 48  5 42]
 [ 8 24 50 23 93 46 89 73 15 60 96 62 13 59  1 85]
 [53 64 98  3 52 60 11 90 83 61 96 93 63 87 79 89]
 [66 47 16 14 58 89 39 58 94  8 88 27 40 84 99 86]
 [18  6 16 35 32 26 53  7 83 81 83 97  2 49 42 44]
 [41 57 53 23 34 21  3 54 42 72 40 54 77 48 86 42]
 [68 66  1 77 47 62  1  5 64 56 31 66 58 86 95  1]
 [36 92 63 14 13 44 86  2 80 41 73 94 46 37 45 89]
 [21 57 16 10  8 28  4 12 18 35 42 16 11 96 17 74]
 [51 89 74 96 35 53 30 60 39 31 47 73 26 62 93 71]
 [15 52 77 38 34 55 18 72 96 16 16 59 13 62 58 66]
 [82 72 72 60 12 94 92 15 80 93 17 19 11 35 64 62]]
📌 Suma por fila:
[ 899  683  920  757  702  797 1082  913  674  747  784  855  465  930
  747  880]
📌 Media por fila:
[56.1875 42.6875 57.5    47.3125 43.875  49.812

In [ ]:
import numpy as np

# Generamos matriz 16x16 con enteros de 0 a 100
matriz = np.random.randint(0, 101, (16, 16))

# Suma por fila
suma_filas = np.sum(matriz, axis=1)

# Media por fila
media_filas = np.mean(matriz, axis=1)

# Mínimos por fila
min_filas = np.min(matriz, axis=1)

# Máximos por fila
max_filas = np.max(matriz, axis=1)


## 03 - 1pt

- Generar un dataframe de 3x4 dimensiones con valores númericos aleatorios [0,10]
- Darle un índice semántico alfanumérico
- Aplicarle una función lambda que obtenga la diferencia entre el máximo y mínimo de cada fila

In [6]:
import pandas as pd
import numpy as np

def diferencia_max_min(df):
    """
    Calcula la diferencia entre el valor máximo y mínimo de cada fila.
    """
    return df.apply(lambda fila: fila.max() - fila.min(), axis=1)

def generar_df_complejo():
    df = pd.DataFrame(np.random.randint(0, 11, (3, 4)),
                      index=["Δ-F1", "β-F2", "Ω-F3"],
                      columns=["X", "Y", "Z", "W"])
    print("📘 DataFrame generado:\n", df)
    diferencias = diferencia_max_min(df)
    print("\n📐 Rango por fila:\n", diferencias)

# Ejecutar
generar_df_complejo()


📘 DataFrame generado:
       X  Y  Z  W
Δ-F1  5  5  7  4
β-F2  3  3  4  4
Ω-F3  4  3  8  0

📐 Rango por fila:
 Δ-F1    3
β-F2    1
Ω-F3    8
dtype: int64


In [7]:
import numpy as np

def procesar_array():
    arr = np.random.randint(-100, 101, (8, 5)).astype(float)
    print("🧾 Array original:\n", arr)

    # Múltiplos de 5 → 100
    mask5 = (arr % 5 == 0)
    arr[mask5] = 100

    # Múltiplos de 3 → NaN
    mask3 = (arr % 3 == 0)
    arr[mask3] = np.nan

    print("\n🎯 Con transformaciones (5 → 100, 3 → NaN):\n", arr)

    # Conteo de NaN por fila
    nan_count = np.isnan(arr).sum(axis=1)
    print("\n❌ NaNs por fila:\n", nan_count)

    # Rellenar NaNs con 0
    arr[np.isnan(arr)] = 0
    print("\n✅ Array final (sin NaNs):\n", arr)

# Ejecutar
procesar_array()


🧾 Array original:
 [[ 17. -97.  93. -32.  55.]
 [ 93.  90. -32. -98. -53.]
 [ 63. -65.   4.  61. -73.]
 [-60. -52.   8. -20. -53.]
 [ 66. -61. -38.  14.  53.]
 [ 81.  52.  66. -18.  -1.]
 [  0.  77. -54. -92. -54.]
 [ 28.  42. -77.  26.  25.]]

🎯 Con transformaciones (5 → 100, 3 → NaN):
 [[ 17. -97.  nan -32. 100.]
 [ nan 100. -32. -98. -53.]
 [ nan 100.   4.  61. -73.]
 [100. -52.   8. 100. -53.]
 [ nan -61. -38.  14.  53.]
 [ nan  52.  nan  nan  -1.]
 [100.  77.  nan -92.  nan]
 [ 28.  nan -77.  26. 100.]]

❌ NaNs por fila:
 [1 1 1 0 1 3 2 1]

✅ Array final (sin NaNs):
 [[ 17. -97.   0. -32. 100.]
 [  0. 100. -32. -98. -53.]
 [  0. 100.   4.  61. -73.]
 [100. -52.   8. 100. -53.]
 [  0. -61. -38.  14.  53.]
 [  0.  52.   0.   0.  -1.]
 [100.  77.   0. -92.   0.]
 [ 28.   0. -77.  26. 100.]]


## 04 - 1pt
- Crear un array de NumPy de dimensiones 8x5, con números enteros aleatorios en el rango [-100, 100]
- Ejecutar en este orden

  1. Reemplazar los valores de todos aquellos números múltiplos de 5 por 100
  2. Reemplazar los valores de todos aquellos números múltiplos de 3 por Nan
   
  2. Averiguar cuantos elementos tienen Nan por fila
  3. Reemplazar los valores de Nan por 0

## 05 - 1pt
- Crear una función que reciba una lista de strings y devuelva una serie de pandas, y convierta el primer y último carácter de la palabra de cada elemento de la serie a mayúsculas

## 06 - 1pt
- La serie de Fibonacci es una sucesión de números, en la cual cada número es la suma de los dos anteriores. Los dos primeros son siempre 0 y 1.
  - $F_0 = 0$
  - $F_1 = 1$
  - $F_n = F_{n-1} + F_{n-2}$
- Crear un generador infinito de números de Fibonacci.

## 07 - 4pt
- Crear una lista de meses de Enero a Diciembre (eje X)
- Generar datos aleatorios para el eje Y, hacerlo 3 veces distintas (Y0, Y1 e Y2)
- Representar las 3 secuencias de datos aleatorios en una sola figura usando matplotlib
- Añadir una leyenda para poder identificar cada secuencia
- Nombrar las 3 secuencias de la siguiente manera ("Facebook", "Twitter", "Instagram")
- Añadir un título y nombres a los dos ejes
- Añadir una anotación (texto y flecha) a uno de los gráficos